export enum MessageType {
  SCRAPE_LEAD = 'SCRAPE_LEAD',
  SCRAPE_ACCOUNT = 'SCRAPE_ACCOUNT',
  SCRAPE_LEAD_RESULT = 'SCRAPE_LEAD_RESULT',
  SCRAPE_ACCOUNT_RESULT = 'SCRAPE_ACCOUNT_RESULT',
  LEAD_CAPTURED = 'LEAD_CAPTURED',
  LEAD_EXTRA_CAPTURED = 'LEAD_EXTRA_CAPTURED',
  LEAD_INSIGHTS_CAPTURED = 'LEAD_INSIGHTS_CAPTURED',
}
