export enum MessageType {
  LEAD_CAPTURED = 'LEAD_CAPTURED',
  LEAD_EXTRA_CAPTURED = 'LEAD_EXTRA_CAPTURED',
  LEAD_INSIGHTS_CAPTURED = 'LEAD_INSIGHTS_CAPTURED',
  COMPANY_CAPTURED = 'COMPANY_CAPTURED',
  COMPANY_EXTRA_CAPTURED = 'COMPANY_EXTRA_CAPTURED',
  LEAD_SEARCH_CAPTURED = 'LEAD_SEARCH_CAPTURED',
}
