export enum MessageType {
  SCRAPE_LEAD = 'SCRAPE_LEAD',
  SCRAPE_COMPANY = 'SCRAPE_COMPANY',
  SCRAPE_LEAD_RESULT = 'SCRAPE_LEAD_RESULT',
  SCRAPE_COMPANY_RESULT = 'SCRAPE_COMPANY_RESULT',
  LEAD_CAPTURED = 'LEAD_CAPTURED',
  LEAD_EXTRA_CAPTURED = 'LEAD_EXTRA_CAPTURED',
  LEAD_INSIGHTS_CAPTURED = 'LEAD_INSIGHTS_CAPTURED',
}
